# Generated by Django 2.0.1 on 2018-02-06 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(max_length=10, null=True, verbose_name='Apartment'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=128, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=10, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6,6}$', message='Should contain exactly 6 numbers')], verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=128, null=True, verbose_name='Street'),
        ),
    ]
