# Generated by Django 2.0.1 on 2018-02-10 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180206_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6,6}$', message='The postal code must consist of 6 digits')], verbose_name='Postcode'),
        ),
    ]
