# Generated by Django 2.0.1 on 2018-02-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_product_date_added'),
        ('remindme', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reminder',
            unique_together={('product', 'email')},
        ),
    ]
