# Generated by Django 2.0.1 on 2018-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=512, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=254, verbose_name='Customer Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=256, verbose_name='Customer Full Name'),
        ),
    ]
